config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  post '/products/select_products', to: "products#select_products", as: :select_products
  put '/products/move_to_inventory', to: "products#move_to_inventory", as: :move_to_inventory
  post '/fridges/select_products_to_list', to: "fridges#select_products_to_list", as: :select_products_to_list
  put '/fridges/move_to_list', to: "fridges#move_to_list", as: :move_to_list
  resources :products
  resources :fridges 
  root to: 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  enum product_cycle: [ :to_buy, :stock, :no_more ]
  belongs_to :user
  PRODUCT_CATEGORIES = ["Vegetables" , "Fruits", "Frozen" , "Meat" , "Seafood" , "Herbs","Soups", "Breads", "Beverages", "Dairy", "Pantry"]
  PRODUCT_MEASUREMENTS = ["tbs" , "oz", "cups" , "lbs" ,"liters", "grams" "packages" , "bottles", "items"]

  validates :name, :product_type, :store, :purchase_date, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :products, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fridges_controller.rb
class FridgesController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper
  before_filter :find_product, only: [:edit, :update, :destroy]
  def index
    session[:selected_products] = {} if params[:clear]
    products_scope = Product.where(product_cycle: 1)
    products_scope = products_scope.where('name ilike ?', "%#{params[:filter]}%") if params[:filter]
    @products = smart_listing_create(:products_stock, products_scope, partial: "fridges/products_stock_list", default_sort: {name: "asc"})
    set_selected_products
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.create(product_params)
    # if @product.save
    #   redirect_to products_path, notice: 'Successfully created.'
    # else
    #   render 'new', alert: 'Error'
    # end
  end

  def edit
  end

  def update
    @product.update_attributes(product_params)
  end

  def destroy
    @product.destroy
  end

  def move_to_list
    if params[:id]
      @products_stock = Product.where(id: params[:id])
    else
      @products_stock = Product.where(id: session[:selected_products].try(:keys))
      session[:selected_products] = {}
    end

    @products_stock.update_all(product_cycle: 0)

    set_selected_products
  end

  def select_products_to_list
    params[:product_selection].each do |key, value|
      if value == "true"
        session[:selected_products] ||= {}
        session[:selected_products][key] = 1
      else
        session[:selected_products].delete(key)
      end
    end

    set_selected_products
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :product_type, :product_cycle, :quantity, :unit_measurement,:expiration_date, :store, :price, :unit_price, :purchase_date, :user_id)
  end

  def set_selected_products
    @selected_products = Product.where(product_cycle: 1).where(id: session[:selected_products].try(:keys))
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper
  
  before_filter :find_product, only: [:edit, :update, :destroy]
  def index
    session[:selected_products] = {} if params[:clear]
    products_scope = Product.where(product_cycle: 0)
    products_scope = products_scope.where('name ilike ?', "%#{params[:filter]}%") if params[:filter]
    @products = smart_listing_create(:products_to_buy, products_scope, partial: "products/products_to_buy_list", default_sort: {name: "asc"})
    
    set_selected_products
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.create(product_params)
  end

  def edit
  end

  def update
    @product.update_attributes(product_params)
  end

  def destroy
    @product.destroy
  end

  def move_to_inventory
    if params[:id]
      @products_to_buy = Product.where(id: params[:id])
    else
      @products_to_buy = Product.where(id: session[:selected_products].try(:keys))
      session[:selected_products] = {}
    end

    @products_to_buy.update_all(product_cycle: 1)

    set_selected_products
  end

  def select_products
    params[:product_selection].each do |key, value|
      if value == "true"
        session[:selected_products] ||= {}
        session[:selected_products][key] = 1
      else
        session[:selected_products].delete(key)
      end
    end

    set_selected_products
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :product_type, :product_cycle, :quantity,:expiration_date, :unit_measurement, :store, :price, :unit_price, :purchase_date, :user_id)
  end

  def set_selected_products
    @selected_products = Product.where(product_cycle: 0).where(id: session[:selected_products].try(:keys))
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/fridges/_product_stock_data.html.haml
- if object.stock?
  %td.text-center= check_box_tag :checkbox, "product_selection[#{object.id}]", session[:selected_products].try(:[], object.id.to_s) == 1, :class => "callback", :autocomplete => "off"
  %td.text-capitalize= object.name
  %td= object.product_type
  %td= object.quantity 
  %td= object.unit_measurement
  %td= object.purchase_date
  %td= object.expiration_date
  %td= object.price
  %td= object.unit_price
  %td.text-capitalize= object.store
  %td.actions.text-center= smart_listing_item_actions [{name: :edit, url: edit_fridge_path(object)}, {name: :destroy, url: fridge_path(object), confirmation: "Are you sure you want to delete this?"}]

app/views/fridges/_products_stock_form.html.haml
%td{colspan: 12}
  .row
    .col-sm-12
      = simple_form_for object, url: object.new_record? ? fridges_path : fridge_path(object), remote: true, html: {class: "form-horizontal"} do |f|
        = f.error_notification 
        .row
          .col-sm-6
            = f.input :name
          .col-sm-6
            = f.input :product_type, collection: Product::PRODUCT_CATEGORIES, prompt: "Select categories"
        .row
          .col-sm-6
            = f.input :quantity
          .col-sm-6
            = f.input :unit_measurement, collection: Product::PRODUCT_MEASUREMENTS, prompt: "Select measurement", include_blank: true
        .row
          .col-sm-6
            = f.input :store
          .col-sm-6
            = f.input :price
        / # = f.input :unit_price
        .row
          .col-sm-6
            = f.input :expiration_date
          .col-sm-6 
            = f.input :purchase_date
        = f.hidden_field :product_cycle, value: 'stock'

        = f.submit "Save", class: "btn btn-success"
        %button.btn.btn-default.cancel Cancel

app/views/fridges/_products_stock_list.html.haml
.table-responsive.pad-top-30
  %table.table.table-striped.table-hover.table-bordered
    %thead
      %tr
        %th.main-color="Check it off" 
        %th= smart_listing.sortable "Name", "name"
        %th= smart_listing.sortable "Product Type", "product_type"
        %th= smart_listing.sortable "Quantity", "quantity"
        %th= smart_listing.sortable "Unit measurement", "unit_measurement"
        %th= smart_listing.sortable "Purchase date", "purchase_date"
        %th= smart_listing.sortable "Expiration date", "expiration_date"
        %th= smart_listing.sortable "Price", "price"
        %th= smart_listing.sortable "Unit price", "unit_price"
        %th= smart_listing.sortable "Store", "store"
        %th
    %tbody
      - smart_listing.collection.each do |product|
        -if product.stock?
          %tr.editable{data: {id: product.id}}
            = smart_listing.render object: product, partial: 'fridges/product_stock_data', locals: {object: product}

      = smart_listing.item_new colspan: 12, link: new_fridge_path

= smart_listing.paginate 
= smart_listing.pagination_per_page_links
#products_to_add_to_list
  = render "fridges/products_to_add_to_list"

app/views/fridges/_products_to_add_to_list.html.haml
- if @selected_products.present?
  = link_to move_to_list_path, :class => "btn btn-primary pull-right", :remote => true, :method => :put do
    %i.glyphicon.glyphicon-send
    = "Move to grocery list"
  = link_to "Clear", fridges_path(:clear => true), :class => "btn btn-link pull-right", :remote => true
  %h5
    = "You have selected"
    = pluralize( @selected_products.count, "item" )
    = "to move to your grocery list."

app/views/fridges/create.js.erb
<%= smart_listing_item :products_stock, :create, @product, @product.valid? ? "fridges/product_stock_data" : "fridges/products_stock_form" %>

app/views/fridges/destroy.js.erb
<%= smart_listing_item :products_stock, :destroy, @product %>

app/views/fridges/edit.html.haml
= render 'products_stock_form'

app/views/fridges/edit.js.erb
<%= smart_listing_item :products_stock, :edit, @product, "fridges/products_stock_form" %>

app/views/fridges/index.html.haml
%h1.tittle.text-center.pad-top-50.pad-bottom-30 My Inventory
= smart_listing_controls_for(:products_stock, {class: "form-inline text-right"}) do
  .form-group.filter.input-append
    = text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :off

  %button.btn.btn-primary.disabled{type: :submit}
    %span.glyphicon.glyphicon-search
      
         
=smart_listing_render(:products_stock, data: {callback_href: select_products_to_list_path})

app/views/fridges/index.js.erb
<%= smart_listing_update :products_stock %>

app/views/fridges/move_to_list.js.erb
<% @products_stock.each do |item| %>
  <%#= smart_listing_item :cart, :update, item, "products/product_to_buy_data" %>
  console.log('tr[data-id="<%= item.id %>"]');
  $('#products_stock').find('tr[data-id="<%= item.id %>"]').remove();
<% end %>
$("#products_stock").smart_listing().fadeLoaded();
$("#products_to_add_to_list").html("<%= escape_javascript(render("fridges/products_to_add_to_list")) %>");

app/views/fridges/new.html.haml
= render 'products_stock_form'

app/views/fridges/new.js.erb
<%= smart_listing_item :products_stock, :new, @product, "fridges/products_stock_form" %>

app/views/fridges/update.js.erb
<%= smart_listing_item :products_stock, :update, @product, @product.valid? ? "fridges/product_stock_data" : "fridges/products_stock_form" %>

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'CHECK IT OFF', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if params[:controller] == 'products' %>
   <li><%= link_to 'Go to inventory', fridges_path, class: "text-orange" %></li>
<% elsif params[:controller] == "fridges"%>
   <li><%= link_to 'See grocery list', products_path,  class: "text-orange"  %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Smart Grocery Tracker'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Smart Grocery Tracker'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header.main-font
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container
        = render 'layouts/messages'
        = yield

app/views/products/_product_to_buy_data.html.haml
- if object.to_buy?
  %td.text-center= check_box_tag :checkbox, "product_selection[#{object.id}]", session[:selected_products].try(:[], object.id.to_s) == 1, :class => "callback", :autocomplete => "off"
  %td.text-capitalize= object.name
  %td= object.product_type
  %td= object.quantity 
  %td= object.unit_measurement
  %td= object.price
  %td.text-capitalize= object.store
  %td.actions.text-center= smart_listing_item_actions [{name: :edit, url: edit_product_path(object)}, {name: :destroy, url: product_path(object), confirmation: "Are you sure you want to delete this?"}]

app/views/products/_products_to_add_to_fridge.html.haml
- if @selected_products.present?
  = link_to move_to_inventory_path, :class => "btn btn-primary pull-right", :remote => true, :method => :put do
    %i.glyphicon.glyphicon-send
    = "Move to inventory"
  = link_to "Clear", products_path(:clear => true), :class => "btn btn-link pull-right", :remote => true
  %h5
    = "You have selected"
    = pluralize( @selected_products.count, "item")
    = "to move to your personal inventory."

app/views/products/_products_to_buy_form.html.haml
%td{colspan: 12}
  .row
    .col-sm-12
      = simple_form_for object, url: object.new_record? ? products_path : product_path(object), remote: true, html: {class: "form-horizontal"} do |f|
        = f.error_notification
        .row
          .col-sm-6
            = f.input :name
          .col-sm-6
            = f.input :product_type, collection: Product::PRODUCT_CATEGORIES, prompt: "Select categories"
        .row
          .col-sm-6
            = f.input :quantity
          .col-sm-6
            = f.input :unit_measurement, collection: Product::PRODUCT_MEASUREMENTS, prompt: "Select measurement", include_blank: true
        .row
          .col-sm-6
            = f.input :store
          .col-sm-6
            = f.input :price
        / # = f.input :unit_price
        .row
          .col-sm-6
            = f.input :expiration_date, include_blank: true
          .col-sm-6 
            = f.input :purchase_date
        = f.hidden_field :product_cycle, value: 'to_buy'

        = f.submit "Save", class: "btn btn-success"
        %button.btn.btn-default.cancel Cancel





    

app/views/products/_products_to_buy_list.html.haml
.table-responsive.pad-top-30
  %table.table.table-striped.table-hover.table-bordered
    %thead
      %tr 
        %th.main-color="Check it off"
        %th= smart_listing.sortable "Name", "name"
        %th= smart_listing.sortable "Product Type", "product_type"
        %th= smart_listing.sortable "Quantity", "quantity"
        %th= smart_listing.sortable "Unit measurement", "unit_measurement"
        %th= smart_listing.sortable "Price", "price"
        %th= smart_listing.sortable "Store", "store"
        %th.actions
    %tbody
      - smart_listing.collection.each do |product|
        -if product.to_buy?
          %tr.editable{data: {id: product.id}}
            = smart_listing.render object: product, partial: 'products/product_to_buy_data', locals: {object: product}

      = smart_listing.item_new colspan: 12, link: new_product_path

= smart_listing.paginate 
= smart_listing.pagination_per_page_links
#products_to_add_to_fridge
  = render "products/products_to_add_to_fridge"



 

app/views/products/create.js.erb
<%= smart_listing_item :products_to_buy, :create, @product, @product.valid? ? "products/product_to_buy_data" : "products/products_to_buy_form" %>

app/views/products/destroy.js.erb
<%= smart_listing_item :products_to_buy, :destroy, @product %>

app/views/products/edit.html.haml
= render 'products_to_buy_form'

app/views/products/edit.js.erb
<%= smart_listing_item :products_to_buy, :edit, @product, "products/products_to_buy_form" %>

app/views/products/index.html.haml
%h1.tittle.text-center.pad-top-50.pad-bottom-30 Grocery List
= smart_listing_controls_for(:products_to_buy, {class: "form-inline text-right"}) do
  .form-group.filter.input-append
    = text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :off

  %button.btn.btn-primary.disabled{type: :submit}
    %span.glyphicon.glyphicon-search
      
         
=smart_listing_render(:products_to_buy, data: {callback_href: select_products_path})

app/views/products/index.js.erb
<%= smart_listing_update :products_to_buy %>

app/views/products/move_to_inventory.js.erb
<% @products_to_buy.each do |item| %>
  <%#= smart_listing_item :cart, :update, item, "products/product_to_buy_data" %>
  console.log('tr[data-id="<%= item.id %>"]');
  $('#products_to_buy').find('tr[data-id="<%= item.id %>"]').remove();
<% end %>
$("#products_to_buy").smart_listing().fadeLoaded();
$("#products_to_add_to_fridge").html("<%= escape_javascript(render("products/products_to_add_to_fridge")) %>");

app/views/products/new.html.haml
= render 'products_to_buy_form'


/ = simple_form_for @product do |f|
/   - if @product.errors.any?
/     #error_explanation
/       %h2
/         = pluralize(@product.errors.count, "error")
/         prohibited
/         this product from being saved:
/       %ul
/         - @product.errors.full_messages.each do |msg|
/           %li= msg

/   = f.input :name, label: 'Product Name: ' 
/   = f.input :product_type, label: 'Product type:'  
/   = f.submit 'Submit', :class => 'button right'

app/views/products/new.js.erb
<%= smart_listing_item :products_to_buy, :new, @product, "products/products_to_buy_form" %>

app/views/products/update.js.erb
<%= smart_listing_item :products_to_buy, :update, @product, @product.valid? ? "products/product_to_buy_data" : "products/products_to_buy_form" %>

app/views/visitors/index.html.erb
<h3>Welcome</h3>